### PR TITLE
Mesh refactor

### PR DESCRIPTION
**Pull request by psbritt**
Let's try this again. This is a small mesh refactor to reincorporate some structured hex mesh capability and add some tet mesh capability. This is required for my source biasing class.

Some methods have also been moved around so that they more closely match their declaration order in their respective .hpp files (like `getHexPlaneIndices`)

I'm also not sure why `getElementVolume` in the tet mesh class is presenting like that on the "Files Changed" tab. I just copied and pasted the code that was originally in `getElementVolumes` and changed it around a bit so it could be used in a method to return a single volume, and had `getElementVolumes` use `getElementVolume` instead.

### CODE REVIEW

**Review by gonuke — APPROVED** [review]
LGTM

**Review by bam241 — APPROVED** [review]
LGTM! merging this evening (or tomorrow morning if no-one complains.)

**Comment by gonuke** [comment]
My only thought is that it would be good to have some more tests with a less uniform mesh?

**Comment by psbritt** [comment]
@gonuke I updated the tests that check volumes to use non-uniform meshes. Do you think the others should be updated too? I'm not sure they would benefit a great deal from a non-uniform mesh.

**Review by gonuke — APPROVED** [review]
LGTM @psbritt

**Pull request merged**
